name: videosummary
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.8 # Ajuster selon la carte graphique
  - h5py
  - numpy
  - pandas
  - tqdm
  - opencv
  - pip
  - pip:
      - py7zr # Pour l'extraction automatisée si besoin
      - matplotlib
